# fly.toml app configuration file generated for oblong-turnip-frontend on 2024-01-25T23:43:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oblong-turnip-frontend"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
